pydjango/crudmaster/crudapi/urls.py
from django.urls import path
from crudapi.views import *


urlpatterns = [
    path('add_user',add_user),
    path('update_user',update_user),
    path('get_user',get_user),
    path('get_user_list',get_user_list),
    path('delete_user',delete_user),

    # API for role

    path('add_role',add_role),
    path('update_role',update_role),
    path('get_role',get_role),
    path('get_role_list',get_role_list),
    path('delete_role',delete_role),


    # API for investor

    path('add_investor',add_investor),
    path('update_investor',update_investor),
    path('get_investor',get_investor),
    path('get_investor_list',get_investor_list),
    path('delete_investor',delete_investor),

    #API for country
    path('add_country',add_country),
    path('update_country',update_country),
    path('get_country',get_country),
    path('get_country_list',get_country_list),
    path('delete_country',delete_country),

    #API for company

    path('add_company',add_company),
    path('update_company',update_company),
    path('get_company',get_company),
    path('get_company_list',get_company_list),
    path('delete_company',delete_company),
   

   #API for Cash in flow

   path('cash_inflow',cash_inflow),
   path('update_cash_inflow',update_cash_inflow),
   path('get_cash_inflow',get_cash_inflow),
   path('get_cash_inflow_list',get_cash_inflow_list),
   path('delete_cash_inflow',delete_cash_inflow),
   

   #API for cash out flow
   path('cash_outflow',cash_outflow),
   path('update_cash_outflow',update_cash_outflow),
   path('get_cash_outflow',get_cash_outflow),
   path('get_cash_outflow_list',get_cash_outflow_list),
   path('delete_cash_outflow',delete_cash_outflow),
   #API for login 
   path('login',login),
   path('log_out',log_out),  
   path('menu_list',menu_list),
   path('add_permission',add_permission),
   path('get_permissions',get_permissions),
   #API for appproved and rejected
   path('approved_inflow_transaction', approved_inflow_transaction),
   path('rejected_inflow_transaction', rejected_inflow_transaction),

   path('approved_outflow_transaction', approved_outflow_transaction),
   path('rejected_outflow_transaction', rejected_outflow_transaction),

   path('ApprovedInflowTransactionList',ApprovedInflowTransactionList),
   path('ApprovedOuflowTransactionList',ApprovedOuflowTransactionList),


   #fetch

   path('fetch_cash_flow_data',fetch_cash_flow_data),

   path('fetch_all_data',fetch_all_data),
  


    # mail

    path('send_email',send_email),
    path('reset_password',reset_password)
]

pydjango/crudmaster/crudapp/urls.py
from django.contrib import admin
from django.urls import path,include
from crudapp.views import *
from django.urls import path
from django.contrib.auth import views as auth_views
urlpatterns = [
    
    path('base',base),
    # path('add_user',add_user,name="add_user"),
    # path('update_user',update_user,name="update_user"),
    path('',login),
    # path('create_role',create_role,name="create_role"),
    #  path('update_role',update_role,name="update_role"),
    # path('add_investor',add_investor,name="add_investor"),
    # path('update_investor',update_investor,name="update_investor"),
    # path('add_company',add_company,name="add_company"),
    # path('update_company',update_company,name="update_company"),
    # path('add_cash_flow',add_cash_flow,name="add_cash_flow"),
    path('dashboard',dashboard,name="dashboard"),
    path('user_list',user_list,name="user_list"),
    path('company_list',company_list,name="company_list"),
    path('investers_list',investers_list,name="investers_list"),
    path('role_list',role_list,name="role_list"),
    path('permission',permission,name="permission"),
    path('inflow_transaction_list',inflow_transaction_list,name="inflow_transaction_list"),
    path('outflow_transaction_list',outflow_transaction_list,name="outflow_transaction_list"),
    path('reports',reports,name="reports"),
    
    path("permission",permission,name="permission"),
    path("logout",logout,name="logout"),


    
    # path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('not_found',not_found,name='not_found'),
    
    path('forget_password',forget_password ,name='forget_password'),
    path('reset_password/<int:id>',reset_password,name='reset_password'),
  
    
]

pydjango/crudmaster/crudmaster/urls.py
from django.contrib import admin
from django.urls import path,include
from crudapp.views import *
urlpatterns = [
    path('',login),
    path('crudapp/',include(('crudapp.urls','crudapp'),namespace='crudapp')),
    path('',include('crudapi.urls')),
   
]

pydjango/crudmaster/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} base{% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha384-..."
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <link
    href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css"
    rel="stylesheet"
  />
  <link href=
  'https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css'
            rel='stylesheet'>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% block static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    {% endblock static %}
  </head>
  <body>
    <div class="dashboard-container">
      <div id="sidebar">
        <div id="menuContent" class="collapse show">
          <div class="side-menu">
            <div class="my-logo">
              <a  class="nav-link"
                ><img class="logo" src="/static/img/logo1.jpg" />
                <span>My Logo </span>
              </a>
            </div>
            <ul class="navbar-nav">
              <a href="{% url 'crudapp:dashboard' %}" class="nav-link px-0" style="color:black">
                <i class="fas fa-tachometer-alt" 
               data-toggle="tooltip"
                  data-placement="top"
                  title="Dashboard"
                > <span style="font-family: Arial,sans-serif; font-weight:500">Dashboard</span> </i> </a>

              {% for menu in menu_list %}
              {% if menu.parentID == 0%}

              <li>
                <a
                  href="#submenu1{{menu.id}}"
                  data-bs-toggle="collapse"
                  class="nav-link px-0"
                  ><div>
                   
                    <i
                    
                      class="{{menu.menuIcon}}"
                      aria-hidden="true"
                      data-toggle="tooltip"
                      data-placement="top"
                      title="{{ menu.menuItem }}" style="color:black;"
                    ></i>
               
                    <span> {{menu.menuItem}}</span>
                    <i
                      class="fa fa-chevron-down icon redirect-icon"
                      aria-hidden="true"
                    style="float:right;"></i>
                  </div>
                </a>
                <ul
                  class="collapse nav flex-column ms-1"
                  id="submenu1{{menu.id}}"
                  data-bs-parent="#menuContent"
                >
                {% for j in menu_list %}
                {% if j.parentID == menu.id %}
                  <li>
                    <a href="{{j.menuPath}}" class="nav-link px-0">
                      <i
                        class="{{j.menuIcon}}"
                        aria-hidden="true"
                        data-toggle="tooltip"
                        data-placement="top"
                        title="{{j.menuItem}}" style="color:black;"
                      ></i>
                      <span>{{j.menuItem}}</span></a
                    >
                  </li>
                  {% endif %}
                  {% endfor %}
                </ul>
              </li>

             

              {% endif %}
              
             {% endfor %}
             
             

               
            </ul>
          </div>
        </div>
      </div>


      <div class="main-content">
      <div class="startnav">
        <div class="navigation-bar">
          <button class="burger-button" id="burger-button">
            <i class="fa-solid fa-bars burger-icon"></i>
          </button>

          <div class="profile-container">
            <div>
              {% comment %} <a href="{% url 'crudapp:login' %}" class="login-button">
                {% if name %}
                 Welcome, {{name }} 
            {% endif %}</a
              > {% endcomment %}
            </div>
            <span style="color:black;margin:5px 10px 0px 0px;">{{name}}</span>
            <label for="profile-checkbox">
              <img src="/static/img/profile-logo.jpg" class="profile-logo" />
            </label>
            <input
              type="checkbox"
              id="profile-checkbox"
              class="profile-checkbox"
            />
            <div class="logout-button-container">
              <a  href="{% url 'crudapp:logout' %}" class="logout-button">
                <p>
                Logout </p><p><i class="fa fa-sign-out" aria-hidden="true"></i
              ></p></a>
            </div>
          </div>
        </div>
      </div>

     
    </div>
    </div>
    {% for msg in messages %}
    <div class="alert {{ msg.tags }} alert-dismissible shadow fade show message message1" role="alert">
       {{msg}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
   
    {% endfor %}
     {% block content %} {% endblock %}

      


 
  
   
    {% comment %}
    <footer id="footer">
      <div
        class="text-center p-2"
        style="background-color: #f2f2f2; font-size: 12px"
      >
        Copyright &copy; 2024 All rights reserved.
      </div>
    </footer>
    {% endcomment %} {% block script %}

   

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="/static/javascript.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.min.js" ></script>
    <script src=
    "https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js">
        </script>
        
       
    {% endblock %}
  </body>
</html>

pydjango/crudmaster/templates/company_list.html
{% extends "base.html" %}
{% block title %} Company List{% endblock title %}
   
 
 
    {% block content %}
    
    <div class="container content-wrapper">
    <div class="tables-data">
          
    <div class="row">
        <div class="col" style="display:flex; justify-content:start;  ">
          <h2>Company List</h2> </div>
         <div class="col">
      <a href=" "   data-bs-toggle="modal" data-bs-target="#add_company"    class="add-button"   data-toggle="tooltip" data-placement="top" title="Add"><i class="fas fa-plus p-icon"></i> Add</a> </div>
      </div>

    <div class="table-responsive">
    <table  class="tables table-hover">
        <thead>
            <tr>
                <th class="text-center">Company Name</th>
                <th class="text-center">Email</th>
                <th class="text-center">Mobile Number</th>
                <th class="text-center"> GSTIN Number</th>
                <th class="text-center">Country</th>
               
                <th class="text-center">Balance</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>
        <tbody>
          {% for company in companies %}
            <tr>
                <td class="text-center">{{company.company_name}}</td>
                <td class="text-center">{{company.email}}</td>
                <td class="text-center">{{company.mobile}}</td>
                <td class="text-center">{{company.gstin}}</td>
                <td class="text-center">{{company.country}}</td>
                <td class="text-center">{{company.balance}}</td>
                <div class="btns">
                    <td class="text-center">
                         
                        <a href="" onclick="setCompanyId({{company.id}})"  data-bs-toggle="modal" data-bs-target="#update_company"  class="edit-buttonn btn bg-success edit-company "   data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
        
                      <a href="" onclick="setCompanyId({{company.id}})" data-bs-toggle="modal" data-bs-target="#delete_company"  class="delete-buttonn btn  bg-danger"  data-toggle="tooltip" data-placement="top" title="Delete" ><i class="fa fa-trash"></i> </td>
                    </div>
            </tr>
            {% endfor %}
            
            <!-- Add more rows as needed -->
        </tbody>
    </table>
</div>
</div>


  <!-- Modal -->
  <div class="modal fade" id="add_company" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLabel">Add Company</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
          
            <div class="modal-body">
              <h5  class="msg text-center" id="msg"> </h5>
                <form action="#" method="POST" id="addCompanyForm">
                    <div class="row">
                    <div class="add-form col-4">
                        <label for="company_name">Company Name:</label>
                        <input type="text" id="company_name1" name="company_name" class="txtOnly" placeholder="Enter Company Name">
                        <span  class="messages" id="company_nameMessage1"></span> 
                    </div>
                    <div class="add-form col-4">
                        <label for="email">Email:</label>
                        <input type="text" id="email1" name="email" placeholder="Enter Email" >
                        <span  class="messages" id="emailMessage1"></span> 
                    </div>
                   
                    <div class="add-form col-4">
                        <label for="mobile_number">Mobile Number:</label>
                        <input type="number" id="mobile1" oninput="truncateInputValue(this)" name="mobile" placeholder="Enter Mobile Number">
                        <span  class="messages" id="mobileMessage1"></span> 
                           
                    </div>
                    <div class="add-form col-4">
                        <label for="number"> GSTIN Number:</label>
                        <input type="text" id="gstin1" name="gstin" placeholder="Enter GSTIN Number"  >
                        <span  class="messages" id="gstinMessage1"></span> 
                    </div>
                   

                    <div class="add-form col-4">
                        <label for="number">Balance:</label>
                        <input type="number" id="balance1" name="balance" placeholder="Enter Balance" >
                        <span  class="messages" id="balanceMessage1"></span> 
                    </div>
                    <div class="add-form col-4">
                        <label for="country">Country:</label>
                        <select id="country1" name="country">
                            <option >Select Country</option>
                            {% for country in countries %}
                            <option value="{{country.id}}" >{{country.country_name}}</option>
                            {% endfor %}
                        </select>
                        <span  class="messages" id="countryMessage1"></span> 
                    </div>
                     
                    
                  
                    
                    <div class="add-form col">
                        <label for="address">Address:</label>
                        
                        <textarea   id="address1" name="address" placeholder="Enter Address"  ></textarea>
                        <span  class="messages" id="addressMessage1"></span> 
                    </div>
                    <div class="modal-footer" style="justify-content:center;">
                        <button type="button" class="btn  close-button" data-bs-dismiss="modal">Close</button>
                        <div class="add-form">
                          <button type="submit" class="btn">Add</button>
                      </div>
                      </div>
                </div>
                </form>
        </div>

        
      </div>
    </div>
  </div>



  {% comment %} update page Modal {% endcomment %}


  <div class="modal fade" id="update_company" tabindex="-1" aria-labelledby="exampleModalLabe2" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLabe2">Update Company</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
       
            <div class="modal-body">
              <h5  class="msg text-center" id="msg1"> </h5>
                <form action="#" method="POST" id="addUserForm">
                    <div class="row">
                    <div class="add-form col-4">
                        <label for="company_name">Company Name:</label>
                        <input type="text" id="company_name" name="company_name" class="txtOnly" placeholder="Enter Company Name">
                        <span  class="messages" id="company_nameMessage"></span> 
                    </div>
                    <div class="add-form col-4">
                        <label for="email">Email:</label>
                        <input type="text" id="email" name="email" placeholder="Enter Email">
                        <span  class="messages" id="emailMessage"></span> 
                    </div>
                   
                    <div class="add-form col-4">
                        <label for="mobile_number">Mobile Number:</label>
                        <input type="number" id="mobile" oninput="truncateInputValue(this)" name="mobile" placeholder="Enter Mobile Number">
                        <span  class="messages" id="mobileMessage"></span> 
                           
                    </div>
                    <div class="add-form col-4">
                        <label for="number"> GSTIN Number:</label>
                        <input type="text" id="gstin" name="gstin" placeholder="Enter GSTIN Number">
                        <span  class="messages" id="gstinMessage"></span> 
                    </div>

                    <div class="add-form col-4">
                        <label for="balance">Balance:</label>
                        <input type="number" id="balance" name="balance" placeholder="Enter Balance"  readonly="readonly"  >
                        <span  class="messages" id="balanceMessage"></span> 
                    </div>
                   
                    <div class="add-form col-4">
                        <label for="country">Country:</label>
                        <select id="country" name="country">
                            <option >Select Country</option>
                            {% for country in countries  %}
                            <option value="{{country.id}}" {% if country.id == single_company.country %}selected{% endif %}>{{country.country_name}}</option>
                            {% endfor %}
                             
                        </select>
                        <span  class="messages" id="countryMessage"></span> 
                    </div>
                     
                     
                   
                  
                    <div class="add-form col">
                        <label for="address">Address:</label>
                        <textarea   id="address" name="address"  placeholder="Enter Address"></textarea>
                        <span  class="messages" id="addressMessage"></span> 
                    </div>
                    <div class="modal-footer" style="justify-content:center;">
                        <button type="button" class="btn  close-button" data-bs-dismiss="modal">Close</button>
                        <div class="add-form">
                          <button type="submit" onclick="return update_company();" id="update-company-button" class="btn">Update</button>
                      </div>
                      </div>
                </div>
                </form>   

        </div>
        
      </div>
    </div>
  </div>



</div>



<div class="modal fade" id="delete_company" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        
            <div class="modal-body">
               
            </p>Are you sure you want to delete this Company</p>
            <div class="modal-footer">
                <button type="button" class="btn  close-button" data-bs-dismiss="modal">Close</button>
                <div class="add-form">
                  <button type="submit" class="btn yes-button">Yes</button>
              </div>
              </div>
        </div>
  
       
      </div>
    </div>
  </div>




  
  <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div style="display:flex; justify-content:end; margin-right:10px; margin-top:10px;">
                
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="padding:0px 0px 10px 0px;">
                <p class="text-green text-center" style="font-size:20px;font-wieght:500px;"
                 id="successMessage"></p>
            </div>

            
        </div>
    </div>
</div>

    {% endblock %}

pydjango/crudmaster/templates/content.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Employee Details</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-...">
   
</head>
<body>
  <div style="background-color: #f4f5f6;">

  <div style="background-color:#ffffff;padding:10px; width:50%;margin:0 auto;border: 2px solid grey; ">
      
        
    <p style="font-weight:bold;">Dear,{{name}}</p>
      <p style="font-weight:bold;">Forget Password? Let's create new one by clicking Reset Link below!</p>

      <a href="http://127.0.0.1:8000/crudapp/reset_password/{{id}}" class="btn-primary">Reset Your Password</a>
        
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="/static/java_script.js"></script>
  <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

pydjango/crudmaster/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> {% block title %}login{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-...">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
  {% block static  %}
  <link rel="stylesheet" href="{% static 'style.css' %}">

  {% endblock static %}
  
</head> 
<body>
 
    <img class="wave-image" src="/static/img/loginsvg.jpg">
     
   
    {% comment %} <img class="onwave-image" src="/static/img/onwave.avif"> {% endcomment %}

    {% for msg in messages %}
    <div class="alert {{ msg.tags }} alert-dismissible shadow fade show message1" role="alert" >
       {{msg}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
    </div>
   
    {% endfor %}  
   
    <div class="login-div col-6">
       
    <div class="login-content" >
        <form method='POST' >
          {% csrf_token %}
    
        
        <div class="login">
            <img  class="avtar-image" src="/static/img/login- profile-image.jpg">
            <h2>Welcome Back</h2>
                  <h3 >Login!</h3>
            <div class="text-input">
                <i class="fa-solid fa-envelope"></i>
                 
                <input type="text" class="input" id="email" name="email" placeholder="Enter Email">
               
            </div>
            <span  class="messages" id="emailMessage"></span> 
            <div class="text-input">
                <i class="fa-solid fa-key"></i>
                <input type="password" class="input" id="password" name="password" placeholder="Enter Password">
                
            </div>
            <span  class="messages" id="passwordMessage"></span> 
            <button class="login-btn" onclick="return loginbutton();"> <i class="fa-solid fa-unlock"></i> Login</button>
             
            
        </div>
        <div style="margin-left:180px; font-weight:700;"><a style="text-decoration:none;" href="{% url 'crudapp:forget_password' %}">Forget Password?</a>
        </div>
       </form>
    </div>
</div>
 
 
 


    {% block script %}
 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="/static/javascript.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
     
    
     
    {% endblock %}
    </body>
    </html>

pydjango/crudmaster/templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> {% block title %}Error Page{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-...">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
  {% block static  %}
  <link rel="stylesheet" href="{% static 'style.css' %}">

  {% endblock static %}
  
</head> 
<body>
    <div class="error-container">
        <h2>Error</h2>
        <p>Sorry, you are not allowed to access this page. Please login to continue.</p>
        <a href="http://127.0.0.1:8000" class="loginbtn">Login</a>
    </div>

    {% block script %}
 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="/static/javascript.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
     
    
     
    {% endblock %}
    </body>
    </html>